apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  db-password: |-
    password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mygoapp:1.9
        ports:
        - containerPort: 8000
        env:
        - name: DB_URL
          value: mysql.default.svc.cluster.local
        volumeMounts:
        - mountPath: /var/run/secrets/
          name: secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secrets
          items:
          - key: db-password
            path: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: backend
